# Site
title:              Joey Navarro
bio:                'Joey Navarro is a Leader and Data Scientist'
description:        "Joey Navarro is a Leader and Data Scientist"
locale:             en_US
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Comments
disqus_shortname:   default

# Social
analytics-id:       "default"
twitter:            NavarroJoey
facebook:           jose.luis.navarro.jr
instagram:          default
github:             joeynavarro
linkedin:           thejoeynavarro
kaggle:             joeynavarroio
medium:             joeynavarro.data

#documents
resume:             https://drive.google.com/file/d/1_Y26F8IKU5QAgDpj8Bi2MIY1eNC1DAOZ/view?usp=sharing


# personal
location:           Austin, Texas
phone:              512-299-1773
email:              joeynavarro.data@gmail.com # change this to your email to receive free emails for your contact submissions via Slapform.com

#certificates

certificate1:
certificate2:       https://drive.google.com/file/d/1wuxVeVd9FZqiJ4CndI8UJrm6xV8Vawh9/view?usp=sharing
certificate3:       https://drive.google.com/file/d/1yBK2XkjJn-ah8STCdy_tUjpvqeF2lS5H/view?usp=sharing
certificate4:
certificate5:       https://drive.google.com/file/d/1w2now6whTA2L8jWc0VCGFOkMXs4fhdgj/view?usp=sharing
certificate6:       https://drive.google.com/file/d/1JWAUVSONnaFvIGdzXJU-VSqGEaCQer1E/view?usp=sharing
certificate7:       https://drive.google.com/file/d/1OG40LlZA_tK6UhwBfXUszmptRug0VWSh/view?usp=sharing
certificate8:       https://drive.google.com/file/d/1hmrZ7LDeRbRguAb_TNM_HuhsXfKEVJ-j/view?usp=sharing
certificate9:       https://drive.google.com/file/d/1vSgMcdSjgJBZM9hrpq5nvI2esJPDtCEo/view?usp=sharing
certificate10:      https://drive.google.com/file/d/1UgKzg81O4-L_54SIkCZq5pLQaX6LyURY/view?usp=sharing
certificate11:      https://drive.google.com/file/d/1hbry0sIIiTKDMvn3VHcl23VnbVIg9o8L/view?usp=sharing
certificate12:      https://drive.google.com/file/d/1o4kAOfnMvtgaurbcP3gI5uXf7ZZc9sV6/view?usp=sharing
certificate13:      https://drive.google.com/file/d/1FLZxCugYo4qO19m9qWZ-oi2ptI8xqrfO/view?usp=sharing
certificate14:      https://drive.google.com/file/d/1CpbIQs7pGBc0e7S__Eepi3DLpjaCiSGs/view?usp=sharing
certificate15:      https://drive.google.com/file/d/1nr4OQugdbPdgCeDEED-zKDdt_zT4H8mq/view?usp=sharing
certificate16:      https://drive.google.com/file/d/1RCEQ-ZGOwmiPbCgfoQ5TZc1tZaYM_SWM/view?usp=sharing
certificate17:      https://drive.google.com/file/d/1M8WeAPq9UNTb1j2m_XDhzLEbeVI9XXkr/view?usp=sharing
certificate18:      https://drive.google.com/file/d/1IeiM4jciej57ixC1unTC7RO-_W-wA8y4/view?usp=sharing
certificate19:      https://drive.google.com/file/d/1vbZP3HVSCsxXHOQb2IhRxKYrQudVlQR4/view?usp=sharing
certificate20:      https://drive.google.com/file/d/1OtEB4sH5XVVfMCmi1FE8diLnxFo93p3-/view?usp=sharing
certificate21:      https://drive.google.com/file/d/1xNTuiwdlB0Bcv-TkLyF4Goxsj2dBPZFP/view?usp=sharing
certificate22:      https://drive.google.com/file/d/1z8ah61fTTjR6nkEquwYr2mLsqFcq8QLY/view?usp=sharing
certificate23:      https://drive.google.com/file/d/1Bm4Vu86uvdNzQvBFlTOQ1R5mlFS2ScOg/view?usp=sharing
certificate24:      https://drive.google.com/file/d/1K-pStrvr4B30OFRXPszWZx0fBzHdDHuf/view?usp=sharing

# Other
background_image:   /images/bg.jpg
# Tip: The color palette and other styles can be configured in /_sass/lib/_vars.scss
slapform_thankyou_page: /thank-you

defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
    layout: post
    author:

# Jekyll
permalink:          /blog/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Gems
gems:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

paginate: 6
paginate_path: "/blog/page:num/"

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, old]
